# Generated by Django 4.2.7 on 2025-09-27 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Classification Metrics',
                'verbose_name_plural': 'Classification Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('classification', models.CharField(choices=[('legitimate', 'Legitimate'), ('spam', 'Spam'), ('phishing', 'Phishing')], max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this sample has been verified by experts')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email Sample',
                'verbose_name_plural': 'Email Samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_content', models.TextField(help_text='The email content to be classified')),
                ('classification', models.CharField(choices=[('legitimate', 'Legitimate'), ('spam', 'Spam'), ('phishing', 'Phishing')], help_text='The classification result', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1) for the classification')),
                ('spam_score', models.FloatField(default=0.0, help_text='Spam probability score')),
                ('phishing_score', models.FloatField(default=0.0, help_text='Phishing probability score')),
                ('legitimate_score', models.FloatField(default=0.0, help_text='Legitimate probability score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Classification',
                'verbose_name_plural': 'Email Classifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
