# Generated by Django 4.2.7 on 2025-09-27 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('detection_type', models.CharField(max_length=20)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('false_positive_rate', models.FloatField()),
                ('true_positive_rate', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Detection Metrics',
                'verbose_name_plural': 'Detection Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('ddos', 'DDoS Attack'), ('mitm', 'MITM Attack'), ('port_scan', 'Port Scan'), ('brute_force', 'Brute Force Attack'), ('malware', 'Malware Communication'), ('suspicious', 'Suspicious Activity')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('target_ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1) for the detection')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('mitigation_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Threat',
                'verbose_name_plural': 'Network Threats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_type', models.CharField(choices=[('http', 'HTTP Request'), ('https', 'HTTPS Request'), ('tcp', 'TCP Connection'), ('udp', 'UDP Connection'), ('dns', 'DNS Query')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_sent', models.PositiveIntegerField(default=0)),
                ('bytes_received', models.PositiveIntegerField(default=0)),
                ('duration', models.FloatField(default=0.0)),
                ('raw_log', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Log',
                'verbose_name_plural': 'Network Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MITMAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('ssl_strip', 'SSL Stripping'), ('certificate_spoof', 'Certificate Spoofing'), ('dns_hijack', 'DNS Hijacking'), ('arp_spoof', 'ARP Spoofing'), ('suspicious_cert', 'Suspicious Certificate')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('target_ip', models.GenericIPAddressField()),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('certificate_issuer', models.CharField(blank=True, max_length=255)),
                ('certificate_subject', models.CharField(blank=True, max_length=255)),
                ('certificate_valid', models.BooleanField(default=True)),
                ('ssl_version', models.CharField(blank=True, max_length=20)),
                ('cipher_suite', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1) for the detection')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('mitigation_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MITM Attack',
                'verbose_name_plural': 'MITM Attacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DDoSAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('volumetric', 'Volumetric Attack'), ('protocol', 'Protocol Attack'), ('application', 'Application Layer Attack'), ('suspicious', 'Suspicious Activity')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('target_ip', models.GenericIPAddressField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('bytes_transferred', models.PositiveBigIntegerField(default=0)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1) for the detection')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('mitigation_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DDoS Attack',
                'verbose_name_plural': 'DDoS Attacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
